{% set name = "akbs" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/akbs-{{ version }}.tar.gz
  sha256: 3032370bdaf7f6a5315df153de60ab46f23b7e3ec984dcec3085b629da07a715

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8

test:
  commands:
    - pip check
    - {{ PYTHON }} -m akbs --version
    - {{ PYTHON }} -m akbs --help
  requires:
    - pip

about:
  home: https://github.com/AaravMalani/AKBS
  summary: A super quick build system for C, C++ and ASM
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/AaravMalani/AKBS

extra:
  recipe-maintainers:
    - AaravMalani
